// import { IOrder, OrderStatus, PaymentStatus } from '../interfaces/order.interface';
// import { PaymentType } from '../interfaces/paymentInfo.interface';
// import { ShippingType } from '../interfaces/shipping.interface';
// import { Role } from '../interfaces/User.interface';

// export const MOCK_ORDERS: IOrder[] = [
//   {
//     _id: 'mock-001',
//     orderNumber: 'ORD-2026-0001',
//     user: {
//       name: 'Martina López',
//       email: 'martina.lopez@gmail.com',
//       role: Role.user,
//       googleID: 'g-001',
//       profilePhoto: '',
//       isActive: true,
//       createdAt: new Date('2025-01-10'),
//       updatedAt: new Date('2025-01-10'),
//     },
//     items: [
//       {
//         product: {} as any,
//         variantSku: 'IPHONE-001-256-BLK',
//         variantLabel: 'iPhone 15 Pro - 256GB - Negro',
//         quantity: 1,
//         price: 1299000,
//         productSnapshot: {
//           brand: 'Apple',
//           model: 'iPhone 15 Pro',
//           image: '',
//         },
//       },
//     ],
//     history: [
//       { status: OrderStatus.PENDING, timestamp: new Date('2026-03-10T14:22:00') },
//     ],
//     shippingInfo: {
//       type: ShippingType.HOME_DELIVERY,
//       cost: 5500,
//     },
//     paymentInfo: {
//       method: PaymentType.BANK_TRANSFER,
//       status: PaymentStatus.APPROVED,
//       amount: 1304500,
//     },
//     status: OrderStatus.PROCESSING_SHIPPING,
//     shippingCost: 5500,
//     total: 1304500,
//     notes: '',
//     createdAt: new Date('2026-03-10T14:22:00'),
//     updatedAt: new Date('2026-03-11T09:00:00'),
//   },
//   {
//     _id: 'mock-002',
//     orderNumber: 'ORD-2026-0002',
//     user: {
//       name: 'Joaquín Ramírez',
//       email: 'joacoramirez@hotmail.com',
//       role: Role.user,
//       googleID: 'g-002',
//       profilePhoto: '',
//       isActive: true,
//       createdAt: new Date('2025-03-01'),
//       updatedAt: new Date('2025-03-01'),
//     },
//     items: [
//       {
//         product: {} as any,
//         variantSku: 'NIKE-AIR-001-43-BLK',
//         variantLabel: 'Nike Air Max - Talle 43 - Negro',
//         quantity: 1,
//         price: 89000,
//         productSnapshot: {
//           brand: 'Nike',
//           model: 'Air Max 90',
//           image: '',
//         },
//       },
//     ],
//     history: [
//       { status: OrderStatus.PENDING, timestamp: new Date('2026-03-10T16:45:00') },
//     ],
//     shippingInfo: {
//       type: ShippingType.PICKUP,
//       pickupPoint: {
//         name: 'Local Centro',
//         address: 'Av. Corrientes 1234, CABA',
//       },
//       cost: 0,
//     },
//     paymentInfo: {
//       method: PaymentType.CASH,
//       status: PaymentStatus.PENDING,
//       amount: 89000,
//     },
//     status: OrderStatus.PENDING,
//     shippingCost: 0,
//     total: 89000,
//     createdAt: new Date('2026-03-10T16:45:00'),
//     updatedAt: new Date('2026-03-10T16:45:00'),
//   },
//   {
//     _id: 'mock-003',
//     orderNumber: 'ORD-2026-0003',
//     user: {
//       name: 'Valentina Gómez',
//       email: 'vgomez@icloud.com',
//       role: Role.user,
//       googleID: 'g-003',
//       profilePhoto: '',
//       isActive: true,
//       createdAt: new Date('2025-06-15'),
//       updatedAt: new Date('2025-06-15'),
//     },
//     items: [
//       {
//         product: {} as any,
//         variantSku: 'SAM-S25-001-128-BLK',
//         variantLabel: 'Samsung Galaxy S25 - 128GB - Negro',
//         quantity: 1,
//         price: 950000,
//         productSnapshot: {
//           brand: 'Samsung',
//           model: 'Galaxy S25',
//           image: '',
//         },
//       },
//       {
//         product: {} as any,
//         variantSku: 'SAM-CASE-001',
//         variantLabel: 'Funda Samsung S25 - Transparente',
//         quantity: 2,
//         price: 8500,
//         productSnapshot: {
//           brand: 'Samsung',
//           model: 'Funda S25',
//           image: '',
//         },
//       },
//     ],
//     history: [
//       { status: OrderStatus.PENDING, timestamp: new Date('2026-03-09T10:00:00') },
//       { status: OrderStatus.PROCESSING_SHIPPING, timestamp: new Date('2026-03-09T15:30:00') },
//       { status: OrderStatus.SHIPPED, timestamp: new Date('2026-03-10T08:00:00') },
//     ],
//     shippingInfo: {
//       type: ShippingType.HOME_DELIVERY,
//       cost: 5500,
//     },
//     paymentInfo: {
//       method: PaymentType.CARD,
//       status: PaymentStatus.APPROVED,
//       transactionId: 'TXN-9876543',
//       paymentDate: new Date('2026-03-09T10:05:00'),
//       amount: 972500,
//     },
//     status: OrderStatus.SHIPPED,
//     shippingCost: 5500,
//     total: 972500,
//     createdAt: new Date('2026-03-09T10:00:00'),
//     updatedAt: new Date('2026-03-10T08:00:00'),
//   },
//   {
//     _id: 'mock-004',
//     orderNumber: 'ORD-2026-0004',
//     user: {
//       name: 'Diego Fernández',
//       email: 'diegof@gmail.com',
//       role: Role.user,
//       googleID: 'g-004',
//       profilePhoto: '',
//       isActive: true,
//       createdAt: new Date('2025-02-20'),
//       updatedAt: new Date('2025-02-20'),
//     },
//     items: [
//       {
//         product: {} as any,
//         variantSku: 'ADIDAS-001-L-WHT',
//         variantLabel: 'Adidas Trefoil Hoodie - Talle L - Blanco',
//         quantity: 1,
//         price: 45000,
//         productSnapshot: {
//           brand: 'Adidas',
//           model: 'Trefoil Hoodie',
//           image: '',
//         },
//       },
//     ],
//     history: [
//       { status: OrderStatus.PENDING, timestamp: new Date('2026-03-08T11:00:00') },
//       { status: OrderStatus.PROCESSING_SHIPPING, timestamp: new Date('2026-03-08T14:00:00') },
//       { status: OrderStatus.SHIPPED, timestamp: new Date('2026-03-09T09:00:00') },
//       { status: OrderStatus.DELIVERED, timestamp: new Date('2026-03-10T12:00:00') },
//     ],
//     shippingInfo: {
//       type: ShippingType.HOME_DELIVERY,
//       cost: 5500,
//     },
//     paymentInfo: {
//       method: PaymentType.ALIAS_TRANSFER,
//       status: PaymentStatus.APPROVED,
//       amount: 50500,
//     },
//     status: OrderStatus.DELIVERED,
//     shippingCost: 5500,
//     total: 50500,
//     createdAt: new Date('2026-03-08T11:00:00'),
//     updatedAt: new Date('2026-03-10T12:00:00'),
//   },
//   {
//     _id: 'mock-005',
//     orderNumber: 'ORD-2026-0005',
//     user: {
//       name: 'Sofía Herrera',
//       email: 'sofi.herrera@yahoo.com',
//       role: Role.user,
//       googleID: 'g-005',
//       profilePhoto: '',
//       isActive: true,
//       createdAt: new Date('2025-07-01'),
//       updatedAt: new Date('2025-07-01'),
//     },
//     items: [
//       {
//         product: {} as any,
//         variantSku: 'LG-TV55-001',
//         variantLabel: 'LG OLED 55" 4K - Negro',
//         quantity: 1,
//         price: 2100000,
//         productSnapshot: {
//           brand: 'LG',
//           model: 'OLED55C3',
//           image: '',
//         },
//       },
//     ],
//     history: [
//       { status: OrderStatus.PENDING, timestamp: new Date('2026-03-07T09:30:00') },
//       { status: OrderStatus.CANCELLED, timestamp: new Date('2026-03-07T11:00:00'), note: 'Cliente solicitó cancelación' },
//     ],
//     shippingInfo: {
//       type: ShippingType.HOME_DELIVERY,
//       cost: 15000,
//     },
//     paymentInfo: {
//       method: PaymentType.CARD,
//       status: PaymentStatus.CANCELLED,
//       amount: 2115000,
//     },
//     status: OrderStatus.CANCELLED,
//     shippingCost: 15000,
//     total: 2115000,
//     notes: 'Cliente solicitó cancelación por error en dirección',
//     createdAt: new Date('2026-03-07T09:30:00'),
//     updatedAt: new Date('2026-03-07T11:00:00'),
//   },
//   {
//     _id: 'mock-006',
//     orderNumber: 'ORD-2026-0006',
//     user: {
//       name: 'Nicolás Torres',
//       email: 'nico.torres@gmail.com',
//       role: Role.user,
//       googleID: 'g-006',
//       profilePhoto: '',
//       isActive: true,
//       createdAt: new Date('2025-09-10'),
//       updatedAt: new Date('2025-09-10'),
//     },
//     items: [
//       {
//         product: {} as any,
//         variantSku: 'PS5-001',
//         variantLabel: 'PlayStation 5 - Standard Edition',
//         quantity: 1,
//         price: 780000,
//         productSnapshot: {
//           brand: 'Sony',
//           model: 'PlayStation 5',
//           image: '',
//         },
//       },
//     ],
//     history: [
//       { status: OrderStatus.PENDING, timestamp: new Date('2026-03-11T08:00:00') },
//     ],
//     shippingInfo: {
//       type: ShippingType.PICKUP,
//       pickupPoint: {
//         name: 'Local Palermo',
//         address: 'Thames 1234, Palermo, CABA',
//       },
//       cost: 0,
//     },
//     paymentInfo: {
//       method: PaymentType.CASH,
//       status: PaymentStatus.PENDING,
//       amount: 780000,
//     },
//     status: OrderStatus.PENDING,
//     shippingCost: 0,
//     total: 780000,
//     createdAt: new Date('2026-03-11T08:00:00'),
//     updatedAt: new Date('2026-03-11T08:00:00'),
//   },
//   {
//     _id: 'mock-007',
//     orderNumber: 'ORD-2026-0007',
//     user: {
//       name: 'Camila Méndez',
//       email: 'cami.mendez@gmail.com',
//       role: Role.user,
//       googleID: 'g-007',
//       profilePhoto: '',
//       isActive: true,
//       createdAt: new Date('2025-11-15'),
//       updatedAt: new Date('2025-11-15'),
//     },
//     items: [
//       {
//         product: {} as any,
//         variantSku: 'NB-550-001-38-PNK',
//         variantLabel: 'New Balance 550 - Talle 38 - Rosa',
//         quantity: 1,
//         price: 98000,
//         productSnapshot: {
//           brand: 'New Balance',
//           model: '550',
//           image: '',
//         },
//       },
//     ],
//     history: [
//       { status: OrderStatus.PENDING, timestamp: new Date('2026-03-10T19:00:00') },
//       { status: OrderStatus.PROCESSING_SHIPPING, timestamp: new Date('2026-03-11T10:00:00') },
//     ],
//     shippingInfo: {
//       type: ShippingType.HOME_DELIVERY,
//       cost: 5500,
//     },
//     paymentInfo: {
//       method: PaymentType.BANK_TRANSFER,
//       status: PaymentStatus.APPROVED,
//       amount: 103500,
//     },
//     status: OrderStatus.PROCESSING_SHIPPING,
//     shippingCost: 5500,
//     total: 103500,
//     createdAt: new Date('2026-03-10T19:00:00'),
//     updatedAt: new Date('2026-03-11T10:00:00'),
//   },
//   {
//     _id: 'mock-008',
//     orderNumber: 'ORD-2026-0008',
//     user: {
//       name: 'Gabriel Moreno',
//       email: 'gabriel.moreno@empresa.com',
//       role: Role.user,
//       googleID: 'g-008',
//       profilePhoto: '',
//       isActive: true,
//       createdAt: new Date('2025-04-22'),
//       updatedAt: new Date('2025-04-22'),
//     },
//     items: [
//       {
//         product: {} as any,
//         variantSku: 'MOTO-G55-001-128',
//         variantLabel: 'Motorola G55 5G - 128GB - Azul',
//         quantity: 2,
//         price: 175000,
//         productSnapshot: {
//           brand: 'Motorola',
//           model: 'G55 5G',
//           image: '',
//         },
//       },
//     ],
//     history: [
//       { status: OrderStatus.PENDING, timestamp: new Date('2026-03-05T10:00:00') },
//       { status: OrderStatus.PROCESSING_SHIPPING, timestamp: new Date('2026-03-05T16:00:00') },
//       { status: OrderStatus.SHIPPED, timestamp: new Date('2026-03-06T10:00:00') },
//       { status: OrderStatus.DELIVERED, timestamp: new Date('2026-03-08T14:00:00') },
//     ],
//     shippingInfo: {
//       type: ShippingType.HOME_DELIVERY,
//       cost: 5500,
//     },
//     paymentInfo: {
//       method: PaymentType.CARD,
//       status: PaymentStatus.APPROVED,
//       transactionId: 'TXN-5543210',
//       paymentDate: new Date('2026-03-05T10:05:00'),
//       amount: 355500,
//     },
//     status: OrderStatus.DELIVERED,
//     shippingCost: 5500,
//     total: 355500,
//     createdAt: new Date('2026-03-05T10:00:00'),
//     updatedAt: new Date('2026-03-08T14:00:00'),
//   },
// ];
